Repository kubernetes-sigs/mdtoc, pull requests merged in 2024-03, with the labels that each got.

#20 Update golangci-lint to v1.57.1, config and fix lints
  .golangci.yml
  hack/verify-golangci-lint.sh
  mdtoc.go
  mdtoc_test.go
  pkg/mdtoc/mdtoc.go
Labels: lgtm, size/L, cncf-cla: yes, approved

#21 Add release job and configurations and general housekeeping
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/dependabot.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  .gitignore
  .goreleaser.yml
  .mdtoc-bom-config.yaml
  Makefile
  go.mod
  go.sum
  mdtoc.go
  mdtoc_test.go
  pkg/mdtoc/mdtoc.go
Labels: lgtm, size/L, cncf-cla: yes, approved

#26 add labels for dependabot prs
  .github/dependabot.yml
Labels: lgtm, size/XS, cncf-cla: yes, approved, kind/cleanup

#27 fix provanance job
  .github/workflows/release.yml
Labels: kind/bug, lgtm, size/XS, cncf-cla: yes, approved, kind/cleanup

#28 add missing github token
  .github/workflows/release.yml
Labels: kind/bug, lgtm, size/XS, cncf-cla: yes, approved

#31 update deprecated option for goreleaser
  .goreleaser.yml
Labels: lgtm, size/XS, cncf-cla: yes, approved, kind/cleanup

#30 bump github.com/gomarkdown/markdown
  go.mod
  go.sum
Labels: lgtm, size/XS, cncf-cla: yes, approved, kind/cleanup

#32 update github.com/gomarkdown/markdown to latest main
  go.mod
  go.sum
Labels: lgtm, size/XS, cncf-cla: yes, approved, kind/cleanup
